### ISSUE TITLE
Number of layers have to match

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#114]
I believe both transformers and LSTM layers require that the number of encoder and decoder layers match. However, they're specified as separate arguments and flags. This makes it hard to do hyperparameter search including them; if one does something like 

```
parameters:
  encoder_layers:
    values: [1, 2]
  decoder_layers:
    values: [1, 2]
```

in a hyperparameter sweep, half the draws will fail at initialization because you'll draw a different number of the two.

I propose that we just standardize this as `--layers`. Thoughts?
